### ISSUE TITLE
Merge parts of Super Gluu w/ oxPush2

### ISSUE THREAD

**Issue by willow9886** [GluuFederation/oxPush2#14]
Let's merge super-gluu partially into oxPush2 to fix issue with Decline button. See issue: https://github.com/GluuFederation/oxPush2/issues/13

**Comment by houssine20** [comment]
Thank you mr @willow9886

**Comment by houssine20** [comment]
I add on the file  /etc/hosts my address ip with hostname like this :

*******houssine@ubuntu:~$sudo nano /etc/hosts

192.168.0.78    ubuntu.gluu.info

::1     ip6-localhost ip6-loopback
fe00::0 ip6-localnet
ff00::0 ip6-mcastprefix
ff02::1 ip6-allnodes
ff02::2 ip6-allrouters

*******

but doesn't resolve , so i think the in /etc/certs/oxpush2_creds.json because gcm ("enabled":false) , or No?

**Comment by houssine20** [comment]
Thank you Mr @NazarYavornytskyy ,Mr @willow9886, Mr @nynymike , Mr @yurem
it is resolved , problem for me is DNS.

**Comment by NazarYavornytskyy** [comment]
Now works as expected
